name: "deploy workflow"

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: echo versions
        run: |
          node --version
          npm --version

      - name: install
        run: npm install --frozen-lockfile --no-progress --non-interactive

      - name: add git credentials & deploy
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          npm run deploy
